// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.6.1
// - protoc             (unknown)
// source: v1/image.proto

package picsalv1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationImageServiceResize = "/picsal.v1.ImageService/Resize"

type ImageServiceHTTPServer interface {
	// Resize 图片缩放
	Resize(context.Context, *ResizeRequest) (*ResizeResponse, error)
}

func RegisterImageServiceHTTPServer(s *http.Server, srv ImageServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/v1/imatge/resize", _ImageService_Resize0_HTTP_Handler(srv))
}

func _ImageService_Resize0_HTTP_Handler(srv ImageServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ResizeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationImageServiceResize)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Resize(ctx, req.(*ResizeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ResizeResponse)
		return ctx.Result(200, reply)
	}
}

type ImageServiceHTTPClient interface {
	Resize(ctx context.Context, req *ResizeRequest, opts ...http.CallOption) (rsp *ResizeResponse, err error)
}

type ImageServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewImageServiceHTTPClient(client *http.Client) ImageServiceHTTPClient {
	return &ImageServiceHTTPClientImpl{client}
}

func (c *ImageServiceHTTPClientImpl) Resize(ctx context.Context, in *ResizeRequest, opts ...http.CallOption) (*ResizeResponse, error) {
	var out ResizeResponse
	pattern := "/v1/imatge/resize"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationImageServiceResize))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
